export * from './authentication/Authentication';
export * from './discoverByGenrePage/DiscoverByGenrePage';
export * from './homePage/HomePage';
export * from './infoPage/InfoPage';
export * from './loginPage/LoginPage';
export * from './moviesListPage/MoviesListPage';
export * from './registerPage/RegisterPage';
export * from './searchPage/SearchPage';
export * from './selectedMovieDetailsPage/SelectedMovieDetailsPage';